bargraph_path: "bar_graph_test_new_modalities/two_bar_chart.png"

fine_bins_per_tick: 12
coarse_bins_per_tick: 3

inference_horizon: 2
gamma: 8.0

T: 6
random_seed: 0

output_dir: "./bar_graph_test_new_modalities"
